language: node_js

node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs"

sudo: false

services:
  - mysql

before_script:
  - mysql -e 'create database webservice;'

env:
  - NODE_ENV=test

cache:
  directories:
    - node_modules
